apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
  namespace: jmedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
    spec:
      nodeSelector:
        nodes.storage: data
      containers:
        - name: sonarr
          image: linuxserver/sonarr:latest
          ports:
            - containerPort: 8989
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: sonarr-config
              mountPath: /config
            - name: sonarr-tv
              mountPath: /tv
            - name: sonarr-downloads
              mountPath: /downloads
      volumes:
        - name: sonarr-config
          hostPath:
            path: /media/sonarr/config
            type: DirectoryOrCreate
        - name: sonarr-tv
          hostPath:
            path: /media/plex/series
            type: DirectoryOrCreate
        - name: sonarr-downloads
          hostPath:
            path: /media/qbittorrent/downloads
            type: DirectoryOrCreate
