reusable:

  namespace: jmedia

  deployment:

    name: sonarr

    image: linuxserver/sonarr:latest

    nodeType: data

    ports:
      - name: http
        containerPort: 8989
        protocol: TCP

    volumes:
      - name: config
        podMount: /config
        hostMount: /media/sonarr/config
        readOnly: false

      - name: movies
        podMount: /movies
        hostMount: /media/plex/movies
        readOnly: false

      - name: downloads
        podMount: /downloads
        hostMount: /media/qbittorrent/downloads
        readOnly: false

  service:
    loadBalancerIP: 192.168.2.217

  ingress:
    disabled: false
