apiVersion: v1
kind: Service
metadata:
  name: ombi
  namespace: jmedia
  annotations:
    metallb.io/loadBalancerIPs: "192.168.2.223"
    metallb.io/address-pool: "internal-pool"
spec:
  type: LoadBalancer
  selector:
    app: ombi
  ports:
    - name: http
      port: 80
      targetPort: 3579
