apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-master-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:JacquesEhlers/homecluster.git
    targetRevision: main
    path: appsets
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ApplyOutOfSyncOnly=true
