apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
  namespace: authelia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authelia
  template:
    metadata:
      labels:
        app: authelia
    spec:
      nodeSelector:
        role: auth
      containers:
        - name: authelia
          image: authelia/authelia:latest
          ports:
            - containerPort: 9091
          env:
            - name: AUTHELIA_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: authelia-secrets
                  key: jwt_secret
            - name: AUTHELIA_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: authelia-secrets
                  key: session_secret
            - name: AUTHELIA_STORAGE_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: authelia-secrets
                  key: storage_encryption_key
          volumeMounts:
            - name: config
              mountPath: /config
            - name: data
              mountPath: /var/lib/authelia
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: config
          projected:
            sources:
              - configMap:
                  name: authelia-config
                  items:
                    - key: configuration.yml
                      path: configuration.yml
              - secret:
                  name: authelia-users
                  items:
                    - key: users.yml
                      path: users.yml
        - name: data
          hostPath:
            path: /k8s/authelia
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: authelia
  namespace: authelia
spec:
  selector:
    app: authelia
  ports:
    - name: http
      port: 9091
      targetPort: 9091
