namespace: jmedia

deployment:
  enabled: true

  name: ""

  image: ""

  replicaCount: 1

  nodeType: config

  ports: []

  extraEnv: []

  volumeMounts: []

  volumes: []

  readinessProbe: {}

  livenessProbe: {}

service:
  disabled: false
  type: LoadBalancer
  loadBalancerIP: ""

ingress:
  disabled: false
  className: nginx
