apiVersion: v1
kind: Node
metadata:
  name: controlplane
  labels:
    node-role.kubernetes.io/control-plane: ""
---
apiVersion: v1
kind: Node
metadata:
  name: jmedia
  labels:
    nodes.storage: data
---
apiVersion: v1
kind: Node
metadata:
  name: node01
  labels:
    nodes.storage: config
