apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: jmedia
  annotations:
    metallb.io/loadBalancerIPs: "192.168.2.218"
    metallb.io/address-pool: "internal-pool"
spec:
  type: LoadBalancer
  selector:
    app: radarr
  ports:
    - name: http
      port: 80
      targetPort: 7878
