reusable:

  namespace: jmedia

  deployment:

    name: radarr

    image: linuxserver/radarr:latest

    nodeType: data

    ports:
      - name: http
        containerPort: 7878
        protocol: TCP

    volumes:
      - name: config
        podMount: /config
        hostMount: /media/radarr/config
        readOnly: false

      - name: movies
        podMount: /movies
        hostMount: /media/plex/movies
        readOnly: false

      - name: downloads
        podMount: /downloads
        hostMount: /media/qbittorrent/downloads
        readOnly: false

  service:
    loadBalancerIP: 192.168.2.218

  ingress:
    disabled: false
