apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: landing
  namespace: jmedia
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - jacquesops.site
      secretName: landing-jacquesops-tls
  rules:
    - host: jacquesops.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: landing
                port:
                  number: 80