apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: plex
  namespace: jmedia
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - plex.jacquesops.site
      secretName: plex-jacquesops-tls
  rules:
    - host: plex.jacquesops.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: plex-web
                port:
                  number: 80