{{- if not (default false .Values.deployment.disabled) }}

{{- $name := required "deployment.name is required" .Values.deployment.name -}}
{{- $image := required "deployment.image is required" .Values.deployment.image -}}

{{- if not (or (eq .Values.deployment.nodeType "config") (eq .Values.deployment.nodeType "data")) }}
{{- fail "deployment.nodeType must be either 'config' or 'data'" }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}

  selector:
    matchLabels:
      app: {{ $name }}

  template:
    metadata:
      labels:
        app: {{ $name }}

    spec:
      nodeSelector:
        nodes.storage: {{ .Values.deployment.nodeType }}

      containers:
        - name: {{ $name }}
          image: {{ $image }}

{{- with .Values.deployment.ports }}
          ports:
{{ toYaml . | nindent 12 }}
{{- end }}

          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"

{{- with .Values.deployment.extraEnv }}
{{ toYaml . | nindent 12 }}
{{- end }}

{{- if .Values.deployment.volumes }}
          volumeMounts:
{{- range .Values.deployment.volumes }}
            - name: {{ .name }}
              mountPath: {{ .podMount }}
              readOnly: {{- if hasKey . "readOnly" }} {{ .readOnly }}{{ else }} true{{ end }}
{{- end }}
{{- end }}

{{- with .Values.deployment.readinessProbe }}
          readinessProbe:
{{ toYaml . | nindent 12 }}
{{- end }}

{{- with .Values.deployment.livenessProbe }}
          livenessProbe:
{{ toYaml . | nindent 12 }}
{{- end }}

{{- if .Values.deployment.volumes }}
      volumes:
{{- range .Values.deployment.volumes }}
        - name: {{ .name }}
          hostPath:
            path: {{ .hostMount }}
            type: {{ default "DirectoryOrCreate" .type }}
{{- end }}
{{- end }}

{{- end }}
