{{- if not (default false .Values.ingress.disabled) }}

{{- $name := required "deployment.name is required" .Values.deployment.name -}}

{{- $host := default (printf "%s.jacquesops.site" $name) .Values.ingress.host -}}

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local:9091/api/verify"
    nginx.ingress.kubernetes.io/auth-signin: "https://auth.jacquesops.site/?rd=$scheme://$host$request_uri"
    nginx.ingress.kubernetes.io/auth-response-headers: "Remote-User,Remote-Groups,Remote-Name,Remote-Email"
{{- with .Values.ingress.extraAnnotations }}
{{ toYaml . | nindent 4 }}
{{- end }}

spec:
  ingressClassName: {{ .Values.ingress.className }}

  tls:
    - hosts:
        - {{ $host }}
      secretName: {{ printf "%s-jacquesops-tls" $name }}

  rules:
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}
                port:
                  number: {{ .Values.service.port }}

{{- end }}
