{{- if not (default false .Values.service.disabled) }}

{{- $name := required "deployment.name is required" .Values.deployment.name -}}
{{- $lbIP := required "service.loadBalancerIP is required" .Values.service.loadBalancerIP -}}
{{- $ports := required "deployment.ports is required" .Values.deployment.ports -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ .Values.namespace }}
  annotations:
    metallb.io/loadBalancerIPs: {{ $lbIP | quote }}
    metallb.io/address-pool: "internal-pool"

spec:
  type: {{ .Values.service.type }}

  selector:
    app: {{ $name }}

  ports:
    {{- range $index, $port := $ports }}
    {{- $portName := default (printf "port-%d" $index) $port.name }}
    - name: {{ $portName }}
      port: {{ if eq $portName "http" }}80{{ else }}{{ $port.containerPort }}{{ end }}
      targetPort: {{ $port.containerPort }}
      protocol: {{ default "TCP" $port.protocol }}
    {{- end }}

{{- end }}
