apiVersion: batch/v1
kind: CronJob
metadata:
  name: hilversum-appointment-check
spec:
  schedule: "0 * * * *"   # every hour
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          imagePullSecrets:
            - name: ghcr-pull
          containers:
            - name: hilversum-check
              image: ghcr.io/jacquesehlers/hilversum-appointment:v2
              imagePullPolicy: Always
              env:
                - name: DATE_1
                  valueFrom:
                    configMapKeyRef:
                      name: hilversum-appointment-config
                      key: DATE_1
                - name: DATE_2
                  valueFrom:
                    configMapKeyRef:
                      name: hilversum-appointment-config
                      key: DATE_2