apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gameoflife
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: gameoflife
  source:
    repoURL: git@github.com:JacquesEhlers/homecluster.git
    targetRevision: main
    path: game-of-life
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
