apiVersion: apps/v1
kind: Deployment
metadata:
  name: lidarr
  namespace: jmedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lidarr
  template:
    metadata:
      labels:
        app: lidarr
    spec:
      nodeSelector:
        nodes.storage: data
      containers:
        - name: lidarr
          image: linuxserver/lidarr:latest
          ports:
            - containerPort: 8686
          env:
            - name: TZ
              value: "Europe/Amsterdam"
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
          volumeMounts:
            - name: lidarr-config
              mountPath: /config
            - name: music
              mountPath: /music
            - name: lidarr-downloads
              mountPath: /downloads
      volumes:
        - name: lidarr-config
          hostPath:
            path: /media/lidarr/config
            type: DirectoryOrCreate
        - name: music
          hostPath:
            path: /media/lidarr/music
            type: DirectoryOrCreate
        - name: lidarr-downloads
          hostPath:
            path: /media/qbittorrent/downloads
            type: DirectoryOrCreate
