apiVersion: v1
kind: Service
metadata:
  name: lidarr
  namespace: jmedia
  annotations:
    metallb.io/loadBalancerIPs: "192.168.2.222"
    metallb.io/address-pool: "internal-pool"
spec:
  type: LoadBalancer
  selector:
    app: lidarr
  ports:
    - name: http
      port: 80
      targetPort: 8686
