reusable:

  namespace: jmedia

  deployment:

    name: lidarr

    image: linuxserver/lidarr:latest

    nodeType: data

    ports:
      - name: http
        containerPort: 8686
        protocol: TCP

    volumes:
      - name: config
        podMount: /config
        hostMount: /media/lidarr/config
        readOnly: false

      - name: music
        podMount: /music
        hostMount: /media/lidarr/music
        readOnly: false

      - name: downloads
        podMount: /downloads
        hostMount: /media/qbittorrent/downloads
        readOnly: false

  service:
    loadBalancerIP: 192.168.2.222

  ingress:
    disabled: false
