apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyseerr
  namespace: jmedia
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      nodeSelector:
        nodes.storage: config
      containers:
        - name: jellyseerr
          image: fallenbagel/jellyseerr:latest
          ports:
            - containerPort: 5055
          env:
            - name: TZ
              value: "Europe/Amsterdam"
          volumeMounts:
            - name: jellyseerr-config
              mountPath: /app/config

      volumes:
        - name: jellyseerr-config
          hostPath:
            path: /media/jellyseerr/config
            type: DirectoryOrCreate
