apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  namespace: jmedia
  annotations:
    metallb.io/loadBalancerIPs: "192.168.2.216"
    metallb.io/address-pool: "internal-pool"
spec:
  type: LoadBalancer
  selector:
    app: jellyseerr
  ports:
    - name: http
      port: 80
      targetPort: 5055
